# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b47e8317c0465171ea7514143f7fd3ec00be91f213530c747e13ad53b6ae19fd2c4aeac15dbb861457e0aeabb7dcd9e8317ff77d9b599ec63b974c8eee5d6b84

test:
  secret_key_base: ef5adedf260832e833917d50063065f6e874fafabb0dd936d1158cd8be0090442aea94bed332a067a549f7c45f3d5489d4945225c7a0829f167ab129a24d8150

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
