default: &default
  action_mailer:
    default_url: 'http://localhost:3000'
    delivery_method: 'test'
  execution_logger:
    type: 'Void'
  custom_tasks: ~
  notifiers:
    mail:
      mail_from: 'Kuroko2 <no-reply@cookpad.com>'
      mail_to: "kuroko@cookpad.com"
    slack:
      webhook_url: ~
  api_basic_authentication_applications:

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
